language: c
compiler:
  - gcc
  - clang

os:
  - linux

addons:
  apt:
    packages:
      - bc
      - gcc-multilib
      - libssl-dev
      - llvm-dev
      - libjemalloc1
      - libjemalloc-dev
      - libnuma-dev
      - python-sphinx
      - libelf-dev
      - selinux-policy-dev
      - libunbound-dev
      - libunbound-dev:i386

before_install: ./.travis/${TRAVIS_OS_NAME}-prepare.sh

before_script: export PATH=$PATH:$HOME/bin

env:
  - OPTS="--disable-ssl"
  - TESTSUITE=1 KERNEL=3.16.54
  - TESTSUITE=1 OPTS="--enable-shared"
  - BUILD_ENV="-m32" OPTS="--disable-ssl"
  - KERNEL=3.16.54 DPDK=1 OPTS="--enable-shared"
  - KERNEL=3.16.54 TESTSUITE=1 DPDK=1
  - KERNEL=3.16.54 DPDK_SHARED=1
  - KERNEL=3.16.54 DPDK_SHARED=1 OPTS="--enable-shared"
  - KERNEL=4.18.20
  - KERNEL=4.17.19
  - KERNEL=4.16.18
  - KERNEL=4.15.18
  - KERNEL=4.14.63
  - KERNEL=4.9.149
  - KERNEL=4.4.148
  - KERNEL=3.19.8
  - KERNEL=3.16.57
  - TESTSUITE=1 LIBS=-ljemalloc

matrix:
  include:
    - os: osx
      compiler: clang
      env: OPTS="--disable-ssl"

script: ./.travis/${TRAVIS_OS_NAME}-build.sh $OPTS

notifications:
  email:
    recipients:
      - ovs-build@openvswitch.org
