language: c
compiler:
  - gcc
  - clang

os:
  - linux

cache:
  directories:
    - dpdk-dir

addons:
  apt:
    packages:
      - bc
      - libssl-dev
      - llvm-dev
      - libjemalloc1
      - libjemalloc-dev
      - libnuma-dev
      - libpcap-dev
      - python3-openssl
      - python3-pip
      - python3-sphinx
      - libelf-dev
      - selinux-policy-dev
      - libunbound-dev
      - libunwind-dev

before_install: ./.travis/${TRAVIS_OS_NAME}-prepare.sh

before_script: export PATH=$PATH:$HOME/bin

env:
  - OPTS="--disable-ssl"
  - TESTSUITE=1 KERNEL=3.16
  - TESTSUITE=1 OPTS="--enable-shared"
  - TESTSUITE=1 DPDK=1
  - TESTSUITE=1 LIBS=-ljemalloc
  - KERNEL_LIST="5.5  4.20 4.19 4.18 4.17 4.16"
  - KERNEL_LIST="4.15 4.14 4.9  4.4  3.19 3.16"
  - AFXDP=1 KERNEL=5.3
  - M32=1 OPTS="--disable-ssl"
  - DPDK=1 OPTS="--enable-shared"
  - DPDK_SHARED=1
  - DPDK_SHARED=1 OPTS="--enable-shared"

matrix:
  include:
    - os: osx
      compiler: clang
      env: OPTS="--disable-ssl"

script: ./.travis/${TRAVIS_OS_NAME}-build.sh $OPTS

notifications:
  email:
    recipients:
      - ovs-build@openvswitch.org
